sudo: required

language: java
jdk:
  - oraclejdk8
node_js: "8.11.3"

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    mvn -B -q -Pprod package docker:build;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push microcks/microcks:latest;
    fi
  - if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
    mvn -B -q -Pprod package docker:build;
    docker tag microcks/microcks microcks/microcks:$TRAVIS_TAG;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push microcks/microcks:$TRAVIS_TAG;
    fi
